name: qh-delta
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.19.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=0.24.0
  - pyyaml>=5.4.0
  - matplotlib>=3.3.0
  - jupyter>=1.0.0
  - notebook>=6.0.0
  - ipykernel>=6.0.0
  - seaborn>=0.11.0
  - pip
  - pip:
    # Add any pip-only packages here if needed
